stages:
- stage: install
  dependsOn: build
  variables: 
    - group: env_test
  jobs:
    # Install the installer task
    - template: install_terraform_task.yml
      parameters:
        name: installer
        directory: $(terraform_installer_dir)  
    # Install the cli task  
    - template: install_terraform_task.yml
      parameters:
        name: cli
        directory: $(terraform_cli_dir)    
    - template: install_delay.yml